# Generated by Django 3.1.5 on 2021-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210221_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
