# Generated by Django 3.1.5 on 2021-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_logo', models.ImageField(upload_to='site_image', verbose_name='لوگو سایت')),
                ('site_copyright', models.CharField(max_length=120, verbose_name='قانون کپی رایت / صاحب سایت')),
                ('short_description', models.CharField(max_length=150, verbose_name='معرفی سایت')),
            ],
        ),
    ]
