# Generated by Django 3.1.5 on 2021-02-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setting', '0002_auto_20210221_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='site_copyright',
            new_name='copyright',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='site_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='site_name',
            new_name='name',
        ),
    ]
